language: python
dist: bionic
python:
    - "3.6"
    - "3.5"
    - "3.7"
    - "pypy3"
    - "3.8"
install:
    - pip install -e .
    - pip install codecov
script:
    - python setup.py test
after_success:
    - codecov
